import JSZip from 'jszip'
import type { GeneratedPythonCode } from './python-generator'

export interface PythonExportOptions {
  userPrompt: string
  generationTimeMs?: number
}

// ─── Clipboard helper (shared with code-viewer) ───────────────────────────────

export async function copyToClipboard(content: string): Promise<void> {
  try {
    await navigator.clipboard.writeText(content)
  } catch {
    // Fallback for older browsers
    const el = document.createElement('textarea')
    el.value = content
    el.style.position = 'fixed'
    el.style.opacity = '0'
    document.body.appendChild(el)
    el.select()
    document.execCommand('copy')
    document.body.removeChild(el)
  }
}

// ─── Single-file download ─────────────────────────────────────────────────────

export function downloadPythonFile(python: string, filename = 'app.py'): void {
  const blob = new Blob([python], { type: 'text/x-python' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// ─── README generator ─────────────────────────────────────────────────────────

function generatePythonReadme(code: GeneratedPythonCode, options: PythonExportOptions): string {
  const { userPrompt, generationTimeMs } = options
  const timestamp = new Date().toISOString()
  const timeInfo = generationTimeMs ? ` in ${(generationTimeMs / 1000).toFixed(1)}s` : ''

  // Extract port from ui.run(...)
  const portMatch = code.python.match(/ui\.run\s*\([^)]*port\s*=\s*(\d+)/i)
  const port = portMatch?.[1] ?? '8080'

  // Extract title
  const titleMatch = code.python.match(/ui\.run\s*\([^)]*title\s*=\s*['"]([^'"]+)['"]/i)
  const appTitle = titleMatch?.[1] ?? 'Streamlit App'

  return `# ${appTitle}

> Generated${timeInfo} on ${timestamp}

## User Request

\`\`\`
${userPrompt}
\`\`\`

## Files

- \`app.py\` — Main Streamlit application
- \`requirements.txt\` — Python dependencies

## Quick Start

### 1. Install dependencies

\`\`\`bash
pip install -r requirements.txt
\`\`\`

### 2. Run the application

\`\`\`bash
streamlit run app.py
\`\`\`

The app will open automatically in your browser at **http://localhost:${port}**.

## Dependencies

- [Streamlit](https://streamlit.io) — Python UI framework
${code.requirements
  .split('\n')
  .filter((l) => !l.startsWith('streamlit'))
  .map((l) => `- ${l.split('>=')[0]}`)
  .join('\n')}

## API Integration Guide

To connect this app to real data sources, replace the sample data dicts/lists in \`app.py\` with API calls.

### Example using httpx (async)

\`\`\`python
import httpx

async def fetch_data():
    async with httpx.AsyncClient() as client:
        response = await client.get('http://your-api/endpoint')
        return response.json()
\`\`\`

Then call \`await fetch_data()\` inside your async page function decorated with \`@ui.page('/')\`.

### Example using requests (sync)

\`\`\`python
import requests

def fetch_data():
    response = requests.get('http://your-api/endpoint')
    return response.json()
\`\`\`

---

*Generated by Interface Generator*
`
}

// ─── ZIP export ───────────────────────────────────────────────────────────────

export async function exportPythonAsZip(
  code: GeneratedPythonCode,
  options: PythonExportOptions,
): Promise<void> {
  const zip = new JSZip()

  zip.file('app.py', code.python)
  zip.file('requirements.txt', code.requirements)
  zip.file('README.md', generatePythonReadme(code, options))

  // Add a minimal .gitignore
  zip.file(
    '.gitignore',
    `__pycache__/
*.pyc
*.pyo
.venv/
venv/
env/
.env
`,
  )

  const blob = await zip.generateAsync({ type: 'blob' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'streamlit-app.zip'
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
