import JSZip from 'jszip'
import type { GeneratedPythonCode } from './python-generator'

export interface PythonExportOptions {
  userPrompt: string
  generationTimeMs?: number
}

// ─── Clipboard helper ─────────────────────────────────────────────────────────

export async function copyToClipboard(content: string): Promise<void> {
  try {
    await navigator.clipboard.writeText(content)
  } catch {
    const el = document.createElement('textarea')
    el.value = content
    el.style.position = 'fixed'
    el.style.opacity = '0'
    document.body.appendChild(el)
    el.select()
    document.execCommand('copy')
    document.body.removeChild(el)
  }
}

// ─── Single-file download ─────────────────────────────────────────────────────

export function downloadPythonFile(python: string, filename = 'app.py'): void {
  const blob = new Blob([python], { type: 'text/x-python' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// ─── README generator ─────────────────────────────────────────────────────────

function generatePythonReadme(code: GeneratedPythonCode, options: PythonExportOptions): string {
  const { userPrompt, generationTimeMs } = options
  const timestamp = new Date().toISOString()
  const timeInfo = generationTimeMs ? ` in ${(generationTimeMs / 1000).toFixed(1)}s` : ''

  // FIX: Extract title from st.set_page_config (was using NiceGUI ui.run regex)
  const titleMatch = code.python.match(/set_page_config\s*\([^)]*page_title\s*=\s*['"]([^'"]+)['"]/i)
  const appTitle = titleMatch?.[1] ?? 'Streamlit App'

  // Build deps list from actual requirements.txt content
  const depLines = code.requirements
    .split('\n')
    .filter((l) => l.trim() && !l.startsWith('streamlit'))
    .map((l) => `- ${l.split('>=')[0].trim()}`)
    .join('\n')

  return `# ${appTitle}

> Generated${timeInfo} on ${timestamp}

## User Request

\`\`\`
${userPrompt}
\`\`\`

## Files

- \`app.py\` — Main Streamlit application
- \`requirements.txt\` — Python dependencies

## Quick Start

### 1. Install dependencies

\`\`\`bash
pip install -r requirements.txt
\`\`\`

### 2. Run the application

\`\`\`bash
streamlit run app.py
\`\`\`

The app will open automatically in your browser at **http://localhost:8501**.

## Dependencies

- [Streamlit](https://streamlit.io) — Python UI framework
${depLines}

## Connecting to real data

Replace the inline sample data lists/dicts in \`app.py\` with API calls:

\`\`\`python
import requests

@st.cache_data(ttl=300)
def fetch_data(endpoint: str):
    response = requests.get(endpoint)
    response.raise_for_status()
    return response.json()
\`\`\`

---

*Generated by Interface Generator*
`
}

// ─── ZIP export ───────────────────────────────────────────────────────────────

export async function exportPythonAsZip(
  code: GeneratedPythonCode,
  options: PythonExportOptions,
): Promise<void> {
  const zip = new JSZip()

  zip.file('app.py', code.python)
  zip.file('requirements.txt', code.requirements)
  zip.file('README.md', generatePythonReadme(code, options))

  zip.file(
    '.gitignore',
    `__pycache__/
*.pyc
*.pyo
.venv/
venv/
env/
.env
`,
  )

  const blob = await zip.generateAsync({ type: 'blob' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'streamlit-app.zip'
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
